version: '3.8'

services:
  projudi-api:
    build: .
    container_name: projudi-api-v4
    ports:
      - "8081:8081"
    environment:
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
      - PLAYWRIGHT_HEADLESS=true
      - MAX_BROWSERS=3
      - PROJUDI_USER=${PROJUDI_USER}
      - PROJUDI_PASS=${PROJUDI_PASS}
      - DEFAULT_SERVENTIA=${DEFAULT_SERVENTIA}
    volumes:
      - ./logs:/app/logs
      - ./downloads:/app/downloads
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - projudi-network

  # Redis (opcional)
  redis:
    image: redis:7-alpine
    container_name: projudi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - projudi-network

volumes:
  redis_data:

networks:
  projudi-network:
    driver: bridge