#!/bin/bash

echo "🧪 Exemplos de teste da API PROJUDI com extrair_partes_detalhadas=false"
echo "=================================================================="

echo ""
echo "1️⃣ Teste básico com partes detalhadas = false:"
echo "curl -X POST \"http://localhost:8081/buscar\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"tipo_busca\": \"processo\","
echo "    \"valor\": \"0508844-37.2007.8.09.0024\","
echo "    \"extrair_partes_detalhadas\": false,"
echo "    \"extrair_partes\": true,"
echo "    \"movimentacoes\": true,"
echo "    \"extrair_anexos\": false"
echo "  }'"

echo ""
echo "2️⃣ Teste com busca por CPF (partes detalhadas = false):"
echo "curl -X POST \"http://localhost:8081/buscar\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"tipo_busca\": \"cpf\","
echo "    \"valor\": \"123.456.789-00\","
echo "    \"extrair_partes_detalhadas\": false,"
echo "    \"extrair_partes\": true,"
echo "    \"movimentacoes\": false,"
echo "    \"extrair_anexos\": false"
echo "  }'"

echo ""
echo "3️⃣ Teste com busca por nome (partes detalhadas = false):"
echo "curl -X POST \"http://localhost:8081/buscar\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"tipo_busca\": \"nome\","
echo "    \"valor\": \"João Silva\","
echo "    \"extrair_partes_detalhadas\": false,"
echo "    \"extrair_partes\": true,"
echo "    \"movimentacoes\": true,"
echo "    \"extrair_anexos\": false"
echo "  }'"

echo ""
echo "4️⃣ Teste com limite de movimentações:"
echo "curl -X POST \"http://localhost:8081/buscar\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"tipo_busca\": \"processo\","
echo "    \"valor\": \"0508844-37.2007.8.09.0024\","
echo "    \"extrair_partes_detalhadas\": false,"
echo "    \"extrair_partes\": true,"
echo "    \"movimentacoes\": true,"
echo "    \"limite_movimentacoes\": 10,"
echo "    \"extrair_anexos\": false"
echo "  }'"

echo ""
echo "5️⃣ Health check da API:"
echo "curl -X GET \"http://localhost:8081/health\""

echo ""
echo "6️⃣ Status da API:"
echo "curl -X GET \"http://localhost:8081/status\""

echo ""
echo "=================================================================="
echo "📝 Notas importantes:"
echo "   - extrair_partes_detalhadas=false: Partes sem endereço, telefone, email, OAB"
echo "   - extrair_partes_detalhadas=true: Partes com informações completas"
echo "   - extrair_partes=false: Não extrai partes (apenas dados básicos do processo)"
echo "   - movimentacoes=false: Não extrai movimentações"
echo "   - extrair_anexos=true: Baixa e processa anexos (mais lento)"
echo ""
echo "🚀 Para executar um teste, copie e cole o comando desejado!"
