version: '3.8'

services:
  projudi-api:
    build: .
    container_name: projudi-api
    restart: unless-stopped
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - PROJUDI_USER=${PROJUDI_USER:-34930230144}
      - PROJUDI_PASS=${PROJUDI_PASS:-Joaquim1*}
      - API_PORT=${API_PORT:-8081}
      - API_HOST=${API_HOST:-0.0.0.0}
      - DEFAULT_SERVENTIA=${DEFAULT_SERVENTIA:-"Advogados - OAB/Matrícula: 25348-N-GO"}
      - SELENIUM_HEADLESS=${SELENIUM_HEADLESS:-true}
      - SELENIUM_TIMEOUT=${SELENIUM_TIMEOUT:-30}
      - SELENIUM_WAIT=${SELENIUM_WAIT:-5}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - RETRY_DELAY=${RETRY_DELAY:-30}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - projudi-network

  redis:
    image: redis:7-alpine
    container_name: projudi-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - projudi-network

volumes:
  redis_data:

networks:
  projudi-network:
    driver: bridge 